# ANTOON-API GIT ACTION
name: Antoon Api Server Git-Action for STAGING

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Actions Sequence
      - name: Start Action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          submodules: true

      # Submodule Update
      - name: Git Sumbmodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      # Set JDK Version
      - name: Set Up Jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Modify Permission
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      # Build Gradle
      - name: Build With Gradle
        run: ./gradlew clean build

      # Login DockerHub
      - name: Login To DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build Docker Container
      - name: Docker Image Build And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: antoonapi/antoon-core-api:latest

      # Deploy with AWS CodeDeploy
      - name: Deploy Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          Default_region_name: ap-northeast-2
          run: |
            aws deploy --region ap-northeast-2 \
            create-deployment \
            --application-name antoon-core-api \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name antoon-core-api-group \
            --github-location repository=depromeet/antoon-api,commitId=${GITHUB_SHA}