name: Antoon API GIT ACTION

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Actions Sequence
      - name: Start action
        uses: actions/checkout@v2

      # Set JDK Version
      - name: Set up jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Modify Permission
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build Gradle
      - name: Build with gradle
        run: ./gradlew clean build

      # Login DockerHub
      - name: Login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}